POOII_T2_DELGADO_JOAQUIN/Models/ErrorViewModel.cs
namespace POOII_T2_DELGADO_JOAQUIN.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

POOII_T2_DELGADO_JOAQUIN/Controllers/InventarioController.cs
using DomainLayer;
using EntityLayer.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace POOII_T2_DELGADO_JOAQUIN.Controllers
{
    public class InventarioController : Controller
    {
        private readonly InventarioService _inventarioService;

        public InventarioController(InventarioService inventarioService)
        {
            _inventarioService = inventarioService;
        }
        public void DropDownList()
        {
            var categorias = _inventarioService.CategoriaDropDownList();
            ViewBag.Categorias = new SelectList(categorias, "Idcategoria", "NombreCategoria");
        }

        public IActionResult IndexProducto()
        {
            var list = _inventarioService.GetProducts();
            return View(list);
        }

        public IActionResult NuevoProducto()
        {
            DropDownList();
            return View();
        }

        [HttpPost]
        public IActionResult NuevoProducto(TbProducto producto)
        {
            if(producto == null)
            {
                return View(producto);
            }

            try
            {
                _inventarioService.Create(producto);
                ViewBag.mensaje1 = "Producto Registrado con éxito.";
                return View();
            }
            catch (Exception ex)
            {
                ViewBag.mensaje2 = "Error al registrar el producto";
                return View(producto);
            }

        }

        public IActionResult Edit(int Id)
        {
            TbProducto producto = new TbProducto();
            producto = _inventarioService.GetPorId(Id);
            DropDownList();
            return View(producto);

        }

        [HttpPost]
        public IActionResult Edit(TbProducto producto)
        {
            _inventarioService.Edit(producto);
            ViewBag.mensaje = "Producto Actualizado correctamente";
            DropDownList();
            return View(producto);
        }

        public IActionResult Eliminar(int Id)
        {
            TbProducto producto = new TbProducto();
            producto = _inventarioService.GetPorId(Id);
            DropDownList();
            return View(producto);

        }

        [HttpPost]
        public IActionResult DeletePro(TbProducto producto)
        {
            _inventarioService.delete(producto.Idproducto);
            ViewBag.mensaje = "Producto Eliminado correctamente";
            return View("Eliminar");
           
        }


        
        
    }
}

POOII_T2_DELGADO_JOAQUIN/Views/Inventario/Edit.cshtml
@using EntityLayer.Models
@model TbProducto
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    TempData["Title"] = "Editar Producto";
}



<div class="card" style="width:50%;">
    <div class="card-header">
        <h1>@TempData["Title"]</h1>
    </div>
    <div class="card-body">
        <form asp-action="Edit" method="post" onsubmit="return confirmUpdate()">
            <input type="hidden" asp-for="Idproducto" />
            <div class="form-group">
                <label asp-for="Nombre" class="form-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Descripcion" class="form-label"></label>
                <textarea asp-for="Descripcion" class="form-control"></textarea>
            </div>

            <div class="form-group">
                <label asp-for="PrecioUnitario" class="form-label"></label>
                <input asp-for="PrecioUnitario" class="form-control" type="number" step="0.01" />
            </div>

            <div class="form-group">
                <label asp-for="Stock" class="form-label"></label>
                <input asp-for="Stock" class="form-control" type="number" />
            </div>

            <div class="form-group">
                <label asp-for="Idcategoria" class="form-label"></label>
                <select asp-for="Idcategoria" class="form-select" asp-items="ViewBag.Categorias">
                    <option value="">-- Seleccionar categoría --</option>
                </select>
                <span asp-validation-for="Idcategoria" class="text-danger"></span>
            </div>
            <div style="margin-top:20px;">
                <button type="submit" class="btn btn-primary">Actualizar</button>
            </div>
        </form>
        <div style="text-align:center;margin-top:20px;">
            <p style="color:green;font-size:20px;">@ViewBag.mensaje</p>
        </div>
        
    </div>

</div>

<script>
    function confirmUpdate() {
        return confirm("¿Está seguro de que desea actualizar este producto?");
    }
</script>

POOII_T2_DELGADO_JOAQUIN/Views/Inventario/Eliminar.cshtml
@using EntityLayer.Models
@model TbProducto
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    TempData["Title"] = "Eliminar Producto";
}



<div class="card" style="width:50%;">
    <div class="card-header">
        <h1>@TempData["Title"]</h1>
    </div>
    <div class="card-body">
        <form asp-action="DeletePro" method="post" onsubmit="return confirmUpdate()">
            <input type="hidden" asp-for="Idproducto" />
            <div class="form-group">
                <label asp-for="Nombre" class="form-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Descripcion" class="form-label"></label>
                <textarea asp-for="Descripcion" class="form-control"></textarea>
            </div>

            <div class="form-group">
                <label asp-for="PrecioUnitario" class="form-label"></label>
                <input asp-for="PrecioUnitario" class="form-control" type="number" step="0.01" />
            </div>

            <div class="form-group">
                <label asp-for="Stock" class="form-label"></label>
                <input asp-for="Stock" class="form-control" type="number" />
            </div>

            <div class="form-group">
                <label asp-for="Idcategoria" class="form-label"></label>
                <select asp-for="Idcategoria" class="form-select" asp-items="ViewBag.Categorias">
                    <option value="">-- Seleccionar categoría --</option>
                </select>
                <span asp-validation-for="Idcategoria" class="text-danger"></span>
            </div>
            <div style="margin-top:20px;">
                <button type="submit" class="btn btn-danger">Eliminar</button>
            </div>

        </form>
        <div style="text-align:center;margin-top:20px;">
            <p style="color:green;font-size:20px;">@ViewBag.mensaje</p>
        </div>
    </div>

</div>

<script>
    function confirmUpdate() {
        return confirm("¿Está seguro de que desea eliminar este producto?");
    }
</script>

POOII_T2_DELGADO_JOAQUIN/Views/Inventario/IndexProducto.cshtml
@using DomainLayer.DTO;
@model IEnumerable<ProductoCategoriaDTO>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    TempData["Title"] = "Lista de Productos";
}

<h1>@TempData["Title"]</h1>
<a asp-action="NuevoProducto" class="btn btn-success">Crear nuevo producto</a>

<table class="table table-bordered" style="text-align:center;">
    <thead>
        <tr>
            <th style="width: 5%;">ID</th>
            <th style="width: 15%;">Nombre</th>
            <th style="width: 20%;">Descripción</th>
            <th style="width: 10%;">Categoría</th>
            <th style="width: 10%;">Precio</th>
            <th style="width: 5%;">Stock</th>
            <th style="width: 12%;">Fecha</th>
            <th style="width: 5%;">Estado</th>
            <th style="width: 25%;">Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var producto in Model)
        {
            <tr>
                <td>@producto.Idproducto</td>
                <td>@producto.Nombre</td>
                <td>@producto.Descripcion</td>
                <td>@producto.NombreCategoria</td>
                <td>S/ @producto.PrecioUnitario</td>
                <td>@producto.Stock</td>
                <td>@producto.FechaRegistro</td>
                <td>@producto.Estado</td>
                <td>
                    <a asp-action="Edit" asp-route-id="@producto.Idproducto" class="btn btn-primary btn-sm">Editar</a>
                    <a asp-action="Eliminar" asp-route-id="@producto.Idproducto" class="btn btn-danger btn-sm">Eliminar</a>
                </td>
            </tr>
        }
    </tbody>
</table>

POOII_T2_DELGADO_JOAQUIN/Views/Inventario/NuevoProducto.cshtml
@using EntityLayer.Models
@model TbProducto
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    TempData["Title"] = "Crear Producto";
}



<div class="card" style="width:50%;">
    <div class="card-header">
        <h1>@TempData["Title"]</h1>
    </div>
    <div class="card-body">
        <form asp-action="NuevoProducto" method="post" id="Formulario">
            <div class="form-group">
                <label asp-for="Nombre" class="form-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Descripcion" class="form-label"></label>
                <textarea asp-for="Descripcion" class="form-control"></textarea>
            </div>

            <div class="form-group">
                <label asp-for="PrecioUnitario" class="form-label"></label>
                <input asp-for="PrecioUnitario" class="form-control" type="number" step="0.01" />
            </div>

            <div class="form-group">
                <label asp-for="Stock" class="form-label"></label>
                <input asp-for="Stock" class="form-control" type="number" />
            </div>

            <div class="form-group">
                <label asp-for="Idcategoria" class="form-label"></label>
                <select asp-for="Idcategoria" class="form-select" asp-items="ViewBag.Categorias">
                    <option value="">-- Seleccionar categoría --</option>
                </select>
                <span asp-validation-for="Idcategoria" class="text-danger"></span>
            </div>

            <div style="margin-top:20px;">
                <button type="submit" class="btn btn-primary">Registrar</button>
                <button type="button" class="btn btn-warning" onclick="Limpiar()">Cancelar</button>
                <a href="./IndexProducto" class="btn btn-secondary">Volver</a>
            </div>
            
        </form>
        <div style="text-align:center;margin-top:20px;">
            <p style="color:green;font-size:20px;">@ViewBag.mensaje1</p>
            <p style="color:red;font-size:20px;">@ViewBag.mensaje2</p>
        </div>
        
    </div>

</div>
<script>
    function Limpiar() {
        document.getElementById('Formulario').reset();
    }
</script>

POOII_T2_DELGADO_JOAQUIN/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - POOII_T2_DELGADO_JOAQUIN</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/POOII_T2_DELGADO_JOAQUIN.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Inventario" asp-action="IndexProducto">POOII_T2_DELGADO_JOAQUIN</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Inventario" asp-action="IndexProducto">Lista Productos</a>
                        </li>
                
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - POOII_T2_DELGADO_JOAQUIN - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>